[workspace]
members = [
    "python_ext",
    "parser",
    "sample_parser",
]
resolver = "2"

[profile.release]
# debug = 1
# lto = "thin"
# codegen-units = 1

# [patch.'https://github.com/microsoft/derivre']
# derivre = { path = "../derivre" }
