[build-system]
requires = ["setuptools==68", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "llguidance"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "mypy"]

[tool.setuptools.packages]
find = { where = ["python"] }

[[tool.setuptools-rust.ext-modules]]
target = "llguidance._lib"
binding = "PyO3"
debug = false
# features = ["aici_llguidance_ctrl/logging"]
# See reference for RustExtension in https://setuptools-rust.readthedocs.io/en/latest/reference.html
