[package]
name = "sample_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
llguidance_parser = { path = "../parser" }
toktrie_hf_tokenizers = { git = "https://github.com/microsoft/toktrie", rev = "7cb20cd594428f5397f6159115d5e070e8c0935f" }
serde_json = "1.0.128"
anyhow = "1.0.87"

[[bin]]
name = "sample_parser"
path = "src/sample_parser.rs"
