[package]
name = "sample_parser"
version = "0.1.0"
edition = "2021"
default-run = "sample_parser"

[dependencies]
llguidance_parser = { path = "../parser" }
toktrie_hf_tokenizers = { git = "https://github.com/microsoft/toktrie", rev = "5e7013ad05081e918809d4ecebb33db7c4aabc69" }
serde_json = "1.0.128"
anyhow = "1.0.87"

[[bin]]
name = "sample_parser"
path = "src/sample_parser.rs"

[[bin]]
name = "schema_tester"
path = "src/schema_tester.rs"
