[package]
name = "llguidance_parser"
version = "0.1.8"
edition = "2021"

[dependencies]
toktrie = { git = "https://github.com/microsoft/toktrie", rev = "8828701d3b1c743472fe61bdf6dab12cdd726ab4" }
derivre = { git = "https://github.com/microsoft/derivre", rev = "30bf07f634426121d1cd003187d96a40af387c19" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
anyhow = "1.0.75"
rustc-hash = "2.0.0"
instant = "0.1.13"

[features]
default = []
logging = []
