[package]
name = "llguidance_parser"
version = "0.2.0"
edition = "2021"

[dependencies]
toktrie = { git = "https://github.com/microsoft/toktrie", rev = "5e7013ad05081e918809d4ecebb33db7c4aabc69" }
derivre = { git = "https://github.com/microsoft/derivre", rev = "02ee497e6e404a0b402b4f68a9abf599d22ed2ed" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }
anyhow = "1.0.75"
rustc-hash = "2.0.0"
instant = "0.1.13"
jsonschema = { version = "0.18.2", default-features = false }
url = "2.5.2"
lazy_static = "1.5.0"

[features]
default = []
logging = []

[lib]
crate-type = ["staticlib", "rlib"]

[build-dependencies]
cbindgen = "0.27.0"
