[package]
name = "llguidance_parser"
version = "0.2.0"
edition = "2021"

[dependencies]
toktrie = { git = "https://github.com/microsoft/toktrie", rev = "a2af4e056ecbc2058a3fe72ac4a6cb05693d600a" }
derivre = { git = "https://github.com/microsoft/derivre", rev = "02ee497e6e404a0b402b4f68a9abf599d22ed2ed" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.132", features = ["preserve_order"] }
anyhow = "1.0.90"
rustc-hash = "2.0.0"
instant = "0.1.13"
jsonschema = { version = "0.24.0", default-features = false }
url = "2.5.2"
lazy_static = "1.5.0"

[features]
default = []
logging = []

[lib]
crate-type = ["staticlib", "rlib"]

[build-dependencies]
cbindgen = "0.27.0"
