[package]
name = "llguidance_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
toktrie = { git = "https://github.com/microsoft/toktrie", rev = "d2cfea79" }
derivre = { git = "https://github.com/microsoft/derivre", rev = "8cb3b0b1" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
anyhow = "1.0.75"
rustc-hash = "2.0.0"

[features]
default = []
logging = []