[package]
name = "llguidance_parser"
version = "0.1.6"
edition = "2021"

[dependencies]
toktrie = { git = "https://github.com/microsoft/toktrie", rev = "bafe0f49e4334cc82c8a0234270dfbac71697db1" }
derivre = { git = "https://github.com/microsoft/derivre", rev = "401b25ff73a738dcf5e2d94f73539f97ed9aed59" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
anyhow = "1.0.75"
rustc-hash = "2.0.0"
instant = "0.1.13"

[features]
default = []
logging = []
